
OPTFLAGS += -m32
CC = arm-linux-gnueabi-gcc
CPP = arm-linux-gnueabi-g++
LIB = "arm-linux-gnueabi-ar cr "
TARGET = "-march=armv6 -mfpu=vfp -mfloat-abi=hard "

all:
	CC=$(CC) CPP=$(CPP) LIB=$(LIB) TARGET=$(TARGET) make -f Makefile
